version: '3'
services:
  app:
    build: ./docker_app
    container_name: uniq_app_cnt
    ports:
      - "8080:3000"
    restart: always
    working_dir: /app
    tty: true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./src:/app
    env_file:
      - ./secret_file/db.env
    command: npm start
    networks:
      - uniq-network
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: uniq_db_cnt
    ports:
      - "27018:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data/db:/data/db
      - ./secret_file/db_init/:/docker-entrypoint-initdb.d
    env_file:
      - ./secret_file/db.env
    command:
      - mongod
    networks:
      - uniq-network
networks:
  uniq-network:
    external: true
