version: '3'
services:
  app:
    build: .
    container_name: uniq_app_cnt
    #network_mode: "host"
    ports:
      - 8080:8080
    restart: always
    working_dir: /app
    tty: true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./src:/app
    command: bash
    #command: node index.js
    networks:
      - uniq-network
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.5-bionic
    container_name: uniq_db_cnt
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./data/db:/data/db
    command:
      - mongod
    networks:
      - uniq-network
networks:
  uniq-network:
    external: true
