version: '3'
services:
  app:
    image: node:12
    container_name: container1
    #network_mode: "host"
    ports:
      - 8080:8080
    restart: always
    working_dir: /app
    stdin_open: true
    volumes:
      - ./src:/app
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.5-bionic
    container_name: container2
    restart: always

    #ports:
    #  - 27099:27017
    volumes:
      - ./data/db:/data/db
    command:
      - mongod
    networks:
      - app-network
networks:
  app-network:
    external: true
